apiVersion: v1
kind: Service
metadata:
  name: dice-game-api-service
  labels:
    name: dice-game-api-service
    app: dice-game-app
spec:
  type: ClusterIP
  ports:
   - port: 3000
  selector:
    name: dice-game-api-pod
    app: dice-game-app